name: Create release

on:
  release:
    types:
      - created
    
jobs:
  proto-zip:
    name: Zip protofiles
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Zip data
      run: zip -r ${{ github.event.repository.name }}.zip src -i \*.proto
      
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.event.repository.name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
