name: Create release

on:
  release:
    types:
      - created
    
jobs:
  proto-zip:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Zip data
      run: zip -r proto.zip src -i \*.proto
      
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: proto.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  proto-zip-swift:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: swift-actions/setup-swift@v1
    - name: swiftprotobuf
      run: |
        wget https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-linux-x86_64.zip
        unzip protoc-21.12-linux-x86_64.zip -d protoc
        export PATH="$(pwd)/protoc/bin:$PATH"
        git clone https://github.com/apple/swift-protobuf.git
        cd swift-protobuf
        git checkout 1.20.3
        swift build -c release
        export PATH="$(pwd)/.build/release:$PATH"
        cd ../
        make protoc-swift
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: swift.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
    

