name: Create release

on:
  release:
    types:
      - created
    
jobs:
  proto-zip:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Zip data
      run: zip -r proto.zip src -i \*.proto
      
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: proto.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  proto-zip-swift:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: swift-actions/setup-swift@v1
    - uses: wizhi/setup-buf@v1
      with:
        version: '0.36.0'

    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'

    - name: swiftprotobuf
      run: |
        git clone https://github.com/apple/swift-protobuf.git
        cd swift-protobuf
        git tag -l
        swift build -c release
        echo "${HOME}/.build/release/protoc-gen-swift" >> $GITHUB_PATH
        cd ../
        protoc -I=. --swift_out=swifttozip/ src/**/*.proto

    - name: Zip data
      run: zip -r swift.zip swifttozip/src -i \*.swift
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: swift.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
    

